version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbit-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build:
      context: ./Producer/producer
      dockerfile: Dockerfile
    container_name: producer
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbit-net
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    build:
      context: ./Consumer/consumer
      dockerfile: Dockerfile
    container_name: consumer
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbit-net
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  rabbit-net:
    driver: bridge